# QuanvLSTM model configuration
model:
  name: "quanvlstm"
  input_dim: 8
  output_dim: 8
  T_out: 1
  num_layers: 2
  hidden_dim_list: [16, 32]
  kernel_size_list: [[3, 3], [3, 3]]
  n_qubits_list: [8, 8] # 每层的量子比特数

# Training configuration
training:
  epochs: 10
  batch_size: 1
  learning_rate: 0.001
  quantum_lr: 0.001 # 量子参数的学习率
  weight_decay: 0.0001
  quantum_weight_decay: 0.0001 # 量子参数的权重衰减
  early_stopping_patience: 20
  save_every: 5
  device: "cuda"
  seed: 42
  checkpoint_path: "./checkpoints/quanvlstm" # 保存模型检查点的路径
  resume: false

# Optimizer configuration
optimizer:
  name: "adam"
  momentum: 0.9

# Scheduler configuration
scheduler:
  name: "step"
  step_size: 30
  gamma: 0.1
  T_max: 200
  patience: 10

# Data configuration
data:
  file_path: "/home/zxh/CQ/dataset/data_small.nc" # 更改为数据文件路径
  var_name: ["CHLA", "PAR", "SST", "sla", "tco", "HCHO", "windspeed", "isoprene"]
  input_seq_len: 8
  target_seq_len: 1
  train_ratio: 0.7
  val_ratio: 0.2
  test_ratio: 0.1
  indices_dir: "/home/zxh/CQ/QWeather/datasets/split/small" # 索引目录路径
  shuffle: true
  num_workers: 4
  normalize: true
  scaler_type: "standard" # 可选: "minmax", "standard"
  scaler_save_path: "/home/zxh/CQ/QWeather/datasets/scaler.pkl" # 标准化器保存路径


# Logging configuration
logging:
  log_dir: "logs/quanvlstm"
  save_logs: true
